app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('', home, name='home'),
	path('view/<int:pk>', viewinf, name='viewinf'),
    path('influencer_details/', influencer_details, name="influencer_details"),
    path('dashboard/', dashboardInf, name="dashboardInf"),
	path('dashboard/filter', dashboardFilter, name="dashboardFilter"),
    path('add_post/', influencerPost, name="influencerPost"),
	path('save_post/', save_post, name='save_post'),
	path('saved_post_view/', saved_post_view, name='saved_post_view'),
	path('remove_saved_post/', remove_saved_post, name='remove_saved_post'),
	path('profile/', profile, name='profile'),
	path('edit_profile/', edit_profile, name='edit_profile'),
	path('personal_post/', personal_post, name='personal_post'),
	path('delete_post/<int:id>/', delete_post, name='delete_post'),
	path('notification/', notification, name='notification'),
	path('accept_request/<int:post_id>/<int:spon_id>/', accept_request, name='accept_request'),
	path('display_modal/<int:work_id>', display_modal, name='display_modal'),
	path('transaction/', transaction, name='transactioninf'),


    path('login/', loginHandle, name='login'),
    path('register/', signupHandle, name='signUp'),
    path('logout/', handleLogout, name='logout'),
    path('company_register/', companySignupHandle, name='companySignupHandle'),



    path('reset_password/',
	 auth_views.PasswordResetView.as_view(template_name = 'authentication/password_reset.html'),
	  name='reset_password'), #submit email form
	path('reset_password_sent/',
	 auth_views.PasswordResetDoneView.as_view(template_name = 'authentication/password_reset_sent.html'),
	  name='password_reset_done'), #Email send and reset
	path('reset/<uidb64>/<token>',
	 auth_views.PasswordResetConfirmView.as_view(template_name = 'authentication/password_reset_form.html'),
	  name='password_reset_confirm'), #link to reset and email
	path('reset_password_complete/',
	 auth_views.PasswordResetCompleteView.as_view(template_name = 'authentication/password_reset_done.html'),
	  name='password_reset_complete'), #password successfully send
]

company/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('',views.dashboardCmp, name='dashboardCmp'),
	path('creation/',views.creation,name="creation"),
	path('dashboard/filter', views.dashboardFilter, name="dashboardFilterCmp"),
	path('dashboard/save_post/', views.saved_post_view, name='cmp_save_post'),
	path('payment/<int:post_id>/', views.payment, name="payment"),
	path('transaction/', views.transaction, name="transaction"),
	path('sponsored/', views.sponsored, name="sponsored"),
	path('accept_mail/<int:id>/', views.accept_mail, name="accept_mail"),
 
 	path('profile/<int:id>/', views.profile_cmp, name='profile_cmp'),
	path('personal_post/<int:id>/', views.personal_post_cmp, name='personal_post_cmp'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path("company/",include("company.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User

# In user Email id and User are same

fields_list=sorted({
    ("Commentary","Commentary"),("ProductReview","ProductReview"),("Comedy","Comedy"),("Reaction","Reaction"),("Q&A","Q&A"),("Interview","Interview"),("Educational","Educational"),("Music","Music"),("Gaming","Gaming"),("Sport","Sport"),("Food","Food"),("Fashion","Fashion"),("Travel","Travel"), ("Fitness", "Fitness")
})

adfields_list=sorted({
    ("Instagram Story + Swipe Up","Instagram Story + Swipe Up"),("Instagram Post","Instagram Post"),("Instagram Reels","Instagram Reels"),("Facebook Story + Swipe Up","Facebook Story + Swipe Up"),("Instagram Post","Instagram Post"),("Facebook Post","Facebook Post"),("YouTube Shorts + Swipe Up","YouTube Shorts + Swipe Up"), ("YouTube Video","YouTube Video"),("Tiktok Video", "Tiktok Video")
})



class Sponsor(models.Model):
    sponsor_id=models.OneToOneField(User,on_delete=models.CASCADE)
    field=models.CharField(max_length=50,choices=fields_list)
    profile_img=models.ImageField(upload_to="profileImg/sponsor/")
    pancard=models.CharField(max_length=12,null=True)
    cin_no=models.CharField(max_length=21,null=True)
    phone_no=models.CharField(max_length=13)
    address=models.TextField(max_length=300)
    website_link=models.URLField(null=True)
    facebook=models.URLField(null=True)
    instagram=models.URLField(null=True)
    twitter=models.URLField(null=True)
    other_link=models.URLField(null=True)
    is_verified=models.BooleanField(null=True,default=False)

    def __str__(self):
        return str(self.sponsor_id.username)

class Influencer(models.Model):
    influencer_id=models.OneToOneField(User,on_delete=models.CASCADE)
    field=models.CharField(max_length=50,choices=fields_list)
    profileImg=models.ImageField(upload_to="profileImg/influencer/")
    dob = models.DateField()
    phone_no=models.CharField(max_length=13)
    bio=models.TextField(max_length=300)
    location=models.CharField(max_length=200)
    
    pancard=models.CharField(max_length=12,null=True, default='NA')
    mode_of_transaction=models.CharField(max_length=25, default='NA', choices=sorted({
        ("1","NetBanking"),("2","Card"),("3","UPI"),("4","Other")
    }))
    bank_name=models.CharField(max_length=25,null=True, default='NA')
    IFSC_code=models.CharField(max_length=15,null=True, default='NA')
    account_no=models.CharField(max_length=15,null=True, default='NA')

    is_verified=models.BooleanField(null=True, default=False)

    def __str__(self):
        return str(self.influencer_id.username)

class InfSocialMedia(models.Model):
    influencer = models.ForeignKey(Influencer, on_delete=models.CASCADE)
    url = models.URLField(null=True)
    social_media = models.CharField(max_length=100, null=True)
    followers = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.influencer.influencer_id.username)


class InfluencerPost(models.Model):
    influencer=models.ForeignKey(Influencer,on_delete=models.CASCADE)
    title=models.CharField(max_length=300)
    price=models.IntegerField(null=True, blank=True, default=0)
    price_desc=models.TextField(max_length=500,null=True)
    day=models.IntegerField(null=True, blank=True, default=5)
    description=models.TextField(max_length=500,null=True)
    field=models.CharField(max_length=50,choices=fields_list)
    adfield=models.CharField(max_length=50,choices=adfields_list,null=True)
    post_img=models.ImageField(upload_to="post/influencer/")

    def __str__(self):
        return str(self.title)+","+str(self.influencer)


class InfSavePost(models.Model):
    who_saved = models.ForeignKey(Influencer, on_delete=models.CASCADE)
    post = models.ForeignKey(InfluencerPost, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.post_id)

class CmpSavePost(models.Model):
    who_saved = models.ForeignKey(Sponsor, on_delete=models.CASCADE)    # later change to Sponser
    post = models.ForeignKey(InfluencerPost, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.post_id)


class Content(models.Model):
    influencer=models.ForeignKey(Influencer,on_delete=models.CASCADE)
    post=models.ForeignKey(InfluencerPost, on_delete=models.CASCADE)
    sponsor = models.ForeignKey(Sponsor, on_delete=models.CASCADE)
    content_link=models.URLField(null=True, blank=True)
    is_accepted=models.BooleanField()
    def __str__(self):
        return str(self.influencer.influencer_id.username)

class Sponsored(models.Model):
    influencer=models.ForeignKey(Influencer,on_delete=models.CASCADE)
    post=models.ForeignKey(InfluencerPost, on_delete=models.CASCADE, null=True)
    sponsor=models.ForeignKey(Sponsor,on_delete=models.CASCADE)
    mode_of_sponsorship=models.CharField(max_length=50,choices=sorted({
        ('online','online')
    }))
    transaction_id=models.CharField(max_length=50)
    amount=models.IntegerField(null=True)
    date = models.DateTimeField(auto_now_add=True, null=True)
    complete = models.BooleanField(default=False, null=True, blank=False)

    def __str__(self):
        return str(self.transaction_id)

company/models.py
from django.db import models

# Create your models here.

company/forms.py
from django.db.models import fields
from app.models import Sponsor
from django.forms import ModelForm

class SponserForm(ModelForm):
    class Meta:
        model=Sponsor
        fields="__all__"
        

company/views.py
import random

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from app.models import *
from app.send_email import sendMail
from company.utils import *
from app.decorators import allowed_users

from .forms import SponserForm

group_cmp = 'Company'



@login_required(login_url='login')
@allowed_users(allowed_roles=[group_cmp])
def dashboardCmp(request):
    posts = InfluencerPost.objects.all().order_by("-id")
    nav_field = [i.field for i in posts]
    saved_posts = CmpSavePost.objects.filter(who_saved=Sponsor.objects.get(sponsor_id=User.objects.get(username=request.user.username)))
    saved_post_ls = [i.post.id for i in saved_posts]
    content = {
               'posts':posts,
               'nav_fields':list(set(nav_field)),
               'saved_post_ls':saved_post_ls
               }
    context_addition(request, content)                      
    return render(request, 'company/index.html', content)


   


@login_required(login_url='login')
@allowed_users(allowed_roles=[group_cmp])
def dashboardFilter(request):
    data = request.GET.get('object')
    if data == 'ALL':
        posts = InfluencerPost.objects.all().order_by('-id')
    else:
        posts = InfluencerPost.objects.filter(field=data).order_by('-id')
    saved_posts = CmpSavePost.objects.filter(who_saved=Sponsor.objects.get(sponsor_id=User.objects.get(username=request.user.username)))
    saved_post_ls = [i.post.id for i in saved_posts]
    content = {'posts':posts,
               'saved_post_ls':saved_post_ls
               }           
    template = render_to_string('company/ajax_temp/dashboard_filter.html', content)
    return JsonResponse({'data': template})    


@login_required(login_url='login')
@allowed_users(allowed_roles=[group_cmp])
def saved_post_view(request):
    saved_posts = CmpSavePost.objects.filter(who_saved=Sponsor.objects.get(sponsor_id=User.objects.get(username=request.user.username))).order_by("-id")
    saved_post_ls = [i.post.id for i in saved_posts]
    content = {'posts':saved_posts,
               'saved_post_ls':saved_post_ls,
               }
    context_addition(request, content)           
    return render(request, 'company/save_post.html', content)




@login_required(login_url='login')
@allowed_users(allowed_roles=[group_cmp])
def payment(request, post_id):
    post = InfluencerPost.objects.filter(id=post_id).first()
    if request.method == 'POST':
        Sponsored.objects.create(
            influencer=post.influencer,
            sponsor=Sponsor.objects.get(sponsor_id=User.objects.get(username=request.user.username)),
            mode_of_sponsorship='online',
            amount=post.price,
            transaction_id=random.randint(11111111, 99999999),
            complete=True,
            post=post
        )
        messages.success(request, 'Payment Successfully Done')
        return JsonResponse('Done', safe=True)
    content = {'post':post, 'id':post_id}
    context_addition(request, content)
    return render(request, 'company/payment.html', content)


@login_required(login_url='login')
def transaction(request):
    sponsor = Sponsor.objects.get(sponsor_id=User.objects.get(username=request.user.username))
    sponsored_details = Sponsored.objects.filter(sponsor=sponsor)
    content = {'sponsored_details': sponsored_details, 'sponsor': sponsor}
    return render(request, 'company/transaction.html', content)





@login_required(login_url='login')
@allowed_users(allowed_roles=[group_cmp])
def sponsored(request):
    sponsor = Sponsor.objects.get(sponsor_id=User.objects.get(username=request.user.username))
    sponsored_details = Sponsored.objects.filter(sponsor=sponsor)
    posts = [i.post for i in sponsored_details]
    content = {'posts':posts}
    context_addition(request, content)
    return render(request, 'company/history.html', content)

@login_required(login_url='login')
@allowed_users(allowed_roles=[group_cmp])
def accept_mail(request, id):
    post = InfluencerPost.objects.filter(id=id).first()
    sponsor = Sponsor.objects.get(sponsor_id=User.objects.get(username=request.user.username))
    content = {
        'post':post,
        'sponsor':sponsor
    }
    sendMail(request,email=[post.influencer.influencer_id.email],mailFor=content ,msg='acceptDeal', subject='Sponsorship Acceptance')
    messages.success(request, 'Send Successfully')
    return redirect('dashboardCmp')


@login_required(login_url='login')
@allowed_users(allowed_roles=[group_cmp])
def creation(request):
    form=SponserForm()
    if request.method=="POST":
        form=SponserForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect("dashboardCmp")
    content={"form":form}
    return render(request,"company/creation.html",content)


@login_required(login_url='login')
def profile_cmp(request, id):
    influencer = Influencer.objects.get(id=id)
    socialmedia = InfSocialMedia.objects.filter(influencer=influencer)
    content = {'socialmedia':socialmedia, 'influencer':influencer}
    return render(request, 'company/profile/profile.html', content)

@login_required(login_url='login')
def personal_post_cmp(request, id):
    influencer = Influencer.objects.get(id=id)
    posts = InfluencerPost.objects.filter(influencer=influencer)
    content = {'influencer':influencer, 'posts':posts}
    return render(request, 'company/profile/post.html', content)

company/templates/company/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<body>
    {% include "navbar.html" %}
    {% include "company/sidecmp_nav.html" %}
    
    
    <div class="content mt-5" style="width: 76%;">
        {% block content %}
        
        {% endblock content %}
        
    </div>





    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        const csrftoken = getCookie('csrftoken');
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

company/templates/company/creation.html
{% extends "authentication/base.html" %}
{% load static %}
{% block title %}
Login
{% endblock title %}
{% block content %}

<div class="container mt-5">

    <style>
        input,
        select,
        textarea {
            background-color: #eee !important;
        }

        #profile-img-in:hover {
            background-color: #cfcfcfce !important;
        }
    </style>

    <div class="pt-5 mt-5" style="height: 100vh;">

        <div class="card card-body w-50 grey-color mx-auto px-5" style="border: 2px groove #eee">
            <form action="{% url 'creation' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div id="personal-details">
                    <h3 class="text-center my-3">Personal Details</h3>
                    <div class="mb-3" style="display: none;">
                        {{form.sponsor_id}}
                    </div>
                    <div class="mb-3 form-floating">
                        {{form.field}}
                        <label for="id_field">Field of interest</label>
                    </div>
                    <div class=" mb-3">
                        <!-- <input type="text" value="choose profile image" id="profile-img-in" readonly style="cursor: pointer;" onclick="fileTrig()"> -->
                        <label for="id_profileImg">Profile Image</label>
                        {{form.profile_img}}

                    </div>
                    <div class="form-floating mb-3">
                        {{form.pancard}}
                        <label for="id_dob">Pancard Number</label>
                    </div>
                    <div class="form-floating mb-3">
                        {{form.cin_no}}
                        <label for="id_dob">CIN Number</label>
                    </div>
                    <div class="form-floating mb-3">
                        {{form.phone_no}}
                        <label for="id_phone_no">Phone Number</label>
                    </div>
                    <div class="form-floating mb-3">
                        {{form.address}}
                        <label for="id_location">Location</label>
                    </div>

                    <div class="mb-3 mt-5 d-flex justify-content-center">
                        <button type="button" class="btn btn-outline-primary w-50" id="next">Next</button>
                    </div>
                </div>

                <div id="social-media-details" style="display: none;">
                    <h3 class="text-center my-3">Social Media Handles</h3>

                    <div class="form-floating mb-3">
                        {{form.website_link}}
                        <label for="id_location">Company Website Link</label>
                    </div>
                    <div class="form-floating mb-3">
                        {{form.facebook}}
                        <label for="id_location">Facebook</label>
                    </div>
                    <div class="form-floating mb-3">
                        {{form.instagram}}
                        <label for="id_location">Instagram</label>
                    </div>
                    <div class="form-floating mb-3">
                        {{form.twitter}}
                        <label for="id_location">Twitter</label>
                    </div>
                    <div class="form-floating mb-3">
                        {{form.other_link}}
                        <label for="id_location">Other Link</label>
                    </div>
                    <div class="form-floating mb-3" style="display: none;">
                        {{form.is_verified}}
                        <label for="id_location">Other Link</label>
                    </div>


                    <div class="mb-3 mt-5 d-flex justify-content-center">
                        <button type="button" class="btn btn-outline-primary w-25 me-3" id="prev">Back</button>
                        <button type="submit" class="btn btn-outline-primary w-25">Submit</button>
                    </div>
                </div>
            </form>
        </div>

    </div>



</div>

<script>
    $("input").addClass("form-control")
    $("select").addClass("form-select")
    $("textarea").addClass("form-control")
    $("#id_sponsor_id").val("{{user.id}}")

    $("#next").click(function () {
        $("#personal-details").hide()
        $("#social-media-details").show()
    })
</script>
{% endblock %}

company/templates/company/index.html
{% extends "company/base.html"%}
{% load static %}
{% load custom_tags %}
{% block title%}Dashboard{% endblock%}
{% block content %}
<link rel="stylesheet" href="{% static 'css/post.css' %}">



<div class="upper-filter mt-5" style="display: grid;grid-template-columns: 1fr 4fr;text-align: center;">
    <div>
        <h5>Feeds</h5>
    </div>
    <div class="filter-menu d-flex justify-content-end">
        <p class="me-3 grey-color" style="cursor: pointer;text-decoration: none;" id="all_data">All</p>
        {% for field in nav_fields %}
        <p class="me-3 grey-color" style="cursor: pointer;text-decoration: none;" id='{{field}}'>{{field}}</p>
        {% endfor %}


    </div>
</div>
<div class="influencer-data">
    <div class="d-flex justify-content-center">
        <div class="spinner-grow text-dark ajaxLoader mt-5" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
    <div class="row justify-content-center mt-3" id="filter_data_post">
        {% for post in posts %}

        {% if post.influencer.influencer_id != request.user.id %}
        <div class="col-3">

            <div class="wrapper">
                <div class="post" style="background: url('{{post.post_img.url}}');background-size: cover;">
                    <div class="overlay">

                        <form action="" method="post" id="save_post_form">
                            {% csrf_token %}
                            <span class="savepost">
                                <button type="button" id="savepost-btn-{{post.id}}" onclick="savePost('{{post.id}}')"><i
                                        class="fas fa-bookmark"></i></button>

                                <button type="button" id="remove-saved-btn-{{post.id}}"
                                    onclick="removeSavedPost('{{post.id}}')"
                                    style="color: black; background-color: white;"><i class="fas fa-bookmark"></i>
                                </button>
                            </span>
                        </form>
                    </div>
                    <a href="{% url 'viewinf' post.id %}" class="about d-flex flex-column"
                        style="text-decoration: none; color: white;margin-top: -58px;text-align: center;">
                        <strong>@{{post.influencer.influencer_id.username}}</strong> <span>{{post.title}} |
                            {{post.field}}</span>

                    </a>
                </div>
            </div>



        </div>
        {% endif %}

        {%endfor%}
    </div>
</div>




<script>
    let nav_fields = {{ nav_fields| safe}};
    const url_path = "{% url 'dashboardFilterCmp' %}";
    let saved_post_list = {{ saved_post_ls }};
    let posts = {{ posts| post_id_list | safe}};
    // console.log(saved_post_list)
    var filter_obj = {
        object: "",
    };
    const ajax_method = {
        url: url_path,
        type: "GET",
        data: filter_obj,
        beforeSend: function () {
            $("#filter_data_post").hide();
            $(".ajaxLoader").show();
        },
        success: function (res) {
            // console.log(res);
            $("#filter_data_post").show();
            $("#filter_data_post").html(res.data);
            $(".ajaxLoader").hide();
        },
    };

    $(document).ready(function () {
        $(".ajaxLoader").hide();
        for (let index = 0; index < nav_fields.length; index++) {
            $("#" + nav_fields[index]).on("click", function () {
                filter_obj.object = nav_fields[index];
                // console.log(filter_obj)
                $.ajax(ajax_method);
            });
        }
        $("#all_data").on("click", function () {
            filter_obj.object = "ALL";
            $.ajax(ajax_method);
        });

        for (let index = 0; index < posts.length; index++) {
            let element = posts[index];
            if (saved_post_list.includes(element)) {
                // saved
                $("#savepost-btn-" + element).hide();
                $("#remove-saved-btn-" + element).show();
            } else {
                // not saved
                $("#savepost-btn-" + element).show();
                $("#remove-saved-btn-" + element).hide();
            }
            $("#savepost-btn-" + element).click(function () {
                $("#savepost-btn-" + element).hide();
                $("#remove-saved-btn-" + element).show();
            });
            $("#remove-saved-btn-" + element).click(function () {
                $("#savepost-btn-" + element).show();
                $("#remove-saved-btn-" + element).hide();
            });
        }
    });

    let savePost = (p_id) => {
        const save_post_details = {
            post_id: p_id,
        };

        const url = "/save_post/";
        fetch(url, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrftoken,
            },
            body: JSON.stringify({ save_post_details: save_post_details }),
        })
            .then((response) => response.json())
            .then((data) => {
                console.log();
            });
    };
    let removeSavedPost = (p_id) => {
        const save_post_details = {
            post_id: p_id,
        };

        const url = "/remove_saved_post/";
        fetch(url, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrftoken,
            },
            body: JSON.stringify({ save_post_details: save_post_details }),
        })
            .then((response) => response.json())
            .then((data) => {
                console.log();
            });
    };
</script>

{% endblock%}

company/templates/company/transaction.html
{% extends "company/base.html"%}
{% load static %}
{% load custom_tags %}
{% block title%}Transaction{% endblock%}
{% block content %}
<div class="w-75 mt-5 mx-auto">
    <h4 class="text-center mb-5">Transaction Details</h4>
    {% for detail in sponsored_details %}
    <div class="card shadow-sm card-body mb-3">
        <div class="row">
            <div class="col-8">
                <p>Payment for {{detail.post.title}} is successfully transfer to {{detail.influencer.influencer_id.username}}'s account </p>
                <p>Transaction id - <span class="text-muted">{{detail.transaction_id}}</span> </p>
            </div>
            <div class="col-4 pe-3" style="text-align: right;"><strong style="color: green;">₹ {{detail.post.price}}</strong></div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock%}