app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('', home, name='home'),
	path('view/<int:pk>', viewinf, name='viewinf'),
    path('influencer_details/', influencer_details, name="influencer_details"),
    path('dashboard/', dashboardInf, name="dashboardInf"),
	path('dashboard/filter', dashboardFilter, name="dashboardFilter"),
    path('add_post/', influencerPost, name="influencerPost"),
	path('save_post/', save_post, name='save_post'),
	path('saved_post_view/', saved_post_view, name='saved_post_view'),
	path('remove_saved_post/', remove_saved_post, name='remove_saved_post'),
	path('profile/', profile, name='profile'),
	path('edit_profile/', edit_profile, name='edit_profile'),
	path('personal_post/', personal_post, name='personal_post'),
	path('delete_post/<int:id>/', delete_post, name='delete_post'),
	path('notification/', notification, name='notification'),
	path('accept_request/<int:post_id>/<int:spon_id>/', accept_request, name='accept_request'),
	path('display_modal/<int:work_id>', display_modal, name='display_modal'),
	path('transaction/', transaction, name='transactioninf'),


    path('login/', loginHandle, name='login'),
    path('register/', signupHandle, name='signUp'),
    path('logout/', handleLogout, name='logout'),
    path('company_register/', companySignupHandle, name='companySignupHandle'),



    path('reset_password/',
	 auth_views.PasswordResetView.as_view(template_name = 'authentication/password_reset.html'),
	  name='reset_password'), #submit email form
	path('reset_password_sent/',
	 auth_views.PasswordResetDoneView.as_view(template_name = 'authentication/password_reset_sent.html'),
	  name='password_reset_done'), #Email send and reset
	path('reset/<uidb64>/<token>',
	 auth_views.PasswordResetConfirmView.as_view(template_name = 'authentication/password_reset_form.html'),
	  name='password_reset_confirm'), #link to reset and email
	path('reset_password_complete/',
	 auth_views.PasswordResetCompleteView.as_view(template_name = 'authentication/password_reset_done.html'),
	  name='password_reset_complete'), #password successfully send
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path("company/",include("company.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User

# In user Email id and User are same

fields_list=sorted({
    ("Commentary","Commentary"),("ProductReview","ProductReview"),("Comedy","Comedy"),("Reaction","Reaction"),("Q&A","Q&A"),("Interview","Interview"),("Educational","Educational"),("Music","Music"),("Gaming","Gaming"),("Sport","Sport"),("Food","Food"),("Fashion","Fashion"),("Travel","Travel"), ("Fitness", "Fitness")
})

adfields_list=sorted({
    ("Instagram Story + Swipe Up","Instagram Story + Swipe Up"),("Instagram Post","Instagram Post"),("Instagram Reels","Instagram Reels"),("Facebook Story + Swipe Up","Facebook Story + Swipe Up"),("Instagram Post","Instagram Post"),("Facebook Post","Facebook Post"),("YouTube Shorts + Swipe Up","YouTube Shorts + Swipe Up"), ("YouTube Video","YouTube Video"),("Tiktok Video", "Tiktok Video")
})



class Sponsor(models.Model):
    sponsor_id=models.OneToOneField(User,on_delete=models.CASCADE)
    field=models.CharField(max_length=50,choices=fields_list)
    profile_img=models.ImageField(upload_to="profileImg/sponsor/")
    pancard=models.CharField(max_length=12,null=True)
    cin_no=models.CharField(max_length=21,null=True)
    phone_no=models.CharField(max_length=13)
    address=models.TextField(max_length=300)
    website_link=models.URLField(null=True)
    facebook=models.URLField(null=True)
    instagram=models.URLField(null=True)
    twitter=models.URLField(null=True)
    other_link=models.URLField(null=True)
    is_verified=models.BooleanField(null=True,default=False)

    def __str__(self):
        return str(self.sponsor_id.username)

class Influencer(models.Model):
    influencer_id=models.OneToOneField(User,on_delete=models.CASCADE)
    field=models.CharField(max_length=50,choices=fields_list)
    profileImg=models.ImageField(upload_to="profileImg/influencer/")
    dob = models.DateField()
    phone_no=models.CharField(max_length=13)
    bio=models.TextField(max_length=300)
    location=models.CharField(max_length=200)
    
    pancard=models.CharField(max_length=12,null=True, default='NA')
    mode_of_transaction=models.CharField(max_length=25, default='NA', choices=sorted({
        ("1","NetBanking"),("2","Card"),("3","UPI"),("4","Other")
    }))
    bank_name=models.CharField(max_length=25,null=True, default='NA')
    IFSC_code=models.CharField(max_length=15,null=True, default='NA')
    account_no=models.CharField(max_length=15,null=True, default='NA')

    is_verified=models.BooleanField(null=True, default=False)

    def __str__(self):
        return str(self.influencer_id.username)

class InfSocialMedia(models.Model):
    influencer = models.ForeignKey(Influencer, on_delete=models.CASCADE)
    url = models.URLField(null=True)
    social_media = models.CharField(max_length=100, null=True)
    followers = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.influencer.influencer_id.username)


class InfluencerPost(models.Model):
    influencer=models.ForeignKey(Influencer,on_delete=models.CASCADE)
    title=models.CharField(max_length=300)
    price=models.IntegerField(null=True, blank=True, default=0)
    price_desc=models.TextField(max_length=500,null=True)
    day=models.IntegerField(null=True, blank=True, default=5)
    description=models.TextField(max_length=500,null=True)
    field=models.CharField(max_length=50,choices=fields_list)
    adfield=models.CharField(max_length=50,choices=adfields_list,null=True)
    post_img=models.ImageField(upload_to="post/influencer/")

    def __str__(self):
        return str(self.title)+","+str(self.influencer)


class InfSavePost(models.Model):
    who_saved = models.ForeignKey(Influencer, on_delete=models.CASCADE)
    post = models.ForeignKey(InfluencerPost, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.post_id)

class CmpSavePost(models.Model):
    who_saved = models.ForeignKey(Sponsor, on_delete=models.CASCADE)    # later change to Sponser
    post = models.ForeignKey(InfluencerPost, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.post_id)


class Content(models.Model):
    influencer=models.ForeignKey(Influencer,on_delete=models.CASCADE)
    post=models.ForeignKey(InfluencerPost, on_delete=models.CASCADE)
    sponsor = models.ForeignKey(Sponsor, on_delete=models.CASCADE)
    content_link=models.URLField(null=True, blank=True)
    is_accepted=models.BooleanField()
    def __str__(self):
        return str(self.influencer.influencer_id.username)

class Sponsored(models.Model):
    influencer=models.ForeignKey(Influencer,on_delete=models.CASCADE)
    post=models.ForeignKey(InfluencerPost, on_delete=models.CASCADE, null=True)
    sponsor=models.ForeignKey(Sponsor,on_delete=models.CASCADE)
    mode_of_sponsorship=models.CharField(max_length=50,choices=sorted({
        ('online','online')
    }))
    transaction_id=models.CharField(max_length=50)
    amount=models.IntegerField(null=True)
    date = models.DateTimeField(auto_now_add=True, null=True)
    complete = models.BooleanField(default=False, null=True, blank=False)

    def __str__(self):
        return str(self.transaction_id)

app/templates/add_details.html
{% extends "base.html" %}
{% load static %}
{% block title %}
profile
{% endblock title %}
{% block content %}

<style>
  input,
  select,
  textarea {
    background-color: #eee !important;
  }

  #profile-img-in:hover {
    background-color: #cfcfcfce !important;
  }
</style>

<div class="pt-5 mt-5" style="height: 100vh;">

  <div class="card card-body w-50 grey-color mx-auto px-5" style="border: 2px groove #eee">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div id="personal-details">
        <h3 class="text-center my-3">Personal Details</h3>
        <div class="mb-3" style="display: none;">
          {{inf_form.influencer_id}}
        </div>
        <div class="mb-3 form-floating">
          {{inf_form.field}}
          <label for="id_field">Field of interest</label>
        </div>
        <div class=" mb-3">
          <!-- <input type="text" value="choose profile image" id="profile-img-in" readonly style="cursor: pointer;" onclick="fileTrig()"> -->
          <label for="id_profileImg">Profile Image</label>
          {{inf_form.profileImg}}

        </div>
        <div class="form-floating mb-3">
          {{inf_form.dob}}
          <label for="id_dob">Date Of Birth</label>
        </div>
        <div class="form-floating mb-3">
          {{inf_form.bio}}
          <label for="id_dob">Bio</label>
        </div>
        <div class="form-floating mb-3">
          {{inf_form.phone_no}}
          <label for="id_phone_no">Phone Number</label>
        </div>
        <div class="form-floating mb-3">
          {{inf_form.location}}
          <label for="id_location">Location</label>
        </div>

        <div class="mb-3 mt-5 d-flex justify-content-center">
          <button type="button" class="btn btn-outline-primary w-50" id="next">Next</button>
        </div>
      </div>

      <div id="social-media-details" style="display: none;">
        <h3 class="text-center my-3">Social Media Handles</h3>

        <div class="form-floating mb-4" style="display: none;">
          {{inf_form.is_verified}}
        </div>
        <div class="row">
          {% for i in for_loop %}
          <div class="col-4 my-3" data-bs-toggle="modal" data-bs-target="#staticBackdrop{{i}}"
            style="text-align: center;cursor: pointer;">
            <div class="py-5 border light-bgcolor" id="div{{i}}"><i class="fas fa-plus" id="plus{{i}}"></i></div>
          </div>
          {% endfor %}

        </div>

        <div style="display: none;">
          {{inf_form.pancard}}
          {{inf_form.mode_of_transaction}}
          {{inf_form.bank_name}}
          {{inf_form.IFSC_code}}
          {{inf_form.account_no}}
          <input type="text" id="social_media_list" name="social_media_list">
        </div>

        <div class="mb-3 mt-5 d-flex justify-content-center">
          <button type="button" class="btn btn-outline-primary w-25 me-3" id="prev">Back</button>
          <button type="submit" class="btn btn-outline-primary w-25">Submit</button>
        </div>
      </div>
    </form>
  </div>

</div>




<!-- modal -->

{% for i in for_loop %}
<div class="modal fade" id="staticBackdrop{{i}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" style="background-color: #eee;">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="" method="post" enctype="multipart/form-data">
          <div class="form-floating mb-3">
            <select class="form-select" id="social_media{{i}}" name="social_media{{i}}"
              aria-label="Floating label select example">
              <option selected hidden></option>
              <option value="youtube">Youtube</option>
              <option value="instagram">Instagram</option>
              <option value="twitter">Twitter</option>
              <option value="facebook">Facebook</option>
              <option value="other">Other</option>
            </select>
            <label for="social_media{{i}}">Select Social Media Handle</label>
          </div>

          <div class="form-floating mb-3">
            <input type="text" class="form-control" id="follower{{i}}" name="follower{{i}}" placeholder="follower">
            <label for="follower{{i}}">Followers</label>
          </div>
          <div class="form-floating mb-3">
            <input type="text" class="form-control" id="url{{i}}" name="url{{i}}" placeholder="url">
            <label for="url{{i}}">URL</label>
          </div>


          <div class="mb-3 d-flex justify-content-center">
            <button type="button" id="btn{{i}}" class="btn btn-outline-primary w-50">
              Add
            </button>
          </div>

        </form>
      </div>
    </div>
  </div>
</div>
{% endfor %}

<script>
  $("input").addClass("form-control")
  $("input").prop("placeholder", "search")
  $("select").addClass("form-select")
  $("textarea").addClass("form-control")
  $("textarea").prop("placeholder", "abc")
  let options = $("option")
  for (let index = 0; index < options.length; index++) {
    let element = options[index];
    if (!element.value) {
      element.hidden = true
      element.innerText = 'choose'
    }

  }
  // $("#id_profileImg").hide()


  $(document).ready(function () {
    $("#id_pancard").val('NA')
    $("#id_bank_name").val('NA')
    $("#id_IFSC_code").val('NA')
    $("#id_account_no").val('NA')
    $("#id_influencer_id").val("{{user.id}}")
    $("#next").click(function () {
      $("#personal-details").hide()
      $("#social-media-details").show()
    })
    $("#prev").click(function () {
      $("#personal-details").show()
      $("#social-media-details").hide()
    })
    let social_handle_obj = {}

    for (let index = 0; index < 6; index++) {
      $("#btn" + index).click(function (e) {
        let social_media = "<p><strong>" + $("#social_media" + index).val().toUpperCase() + "</strong></p>"
        let follower = "<p>" + $("#follower" + index).val() + " followers</p>"

        $("#plus" + index).hide()
        $("#div" + index).html(social_media + follower)
        $("#div" + index).removeClass('py-5')
        $("#div" + index).addClass('pt-3 pb-4')
        social_handle_obj[index] = {
          "social_media": $("#social_media" + index).val(),
          "follower": $("#follower" + index).val(),
          "url": $("#url" + index).val()
        }

        $("#social_media_list").val(JSON.stringify(social_handle_obj))
        console.log(social_handle_obj)
        $(".btn-close").trigger("click")
      })

    }


  })


  $("#id_dob").attr('type', 'date')

</script>
{% endblock content %}

app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    
</head>

<body>
    {% include "navbar.html" %}
    
    {% block content %}

    {% endblock content %}

    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        const csrftoken = getCookie('csrftoken');
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/dashboard.html
{% extends "dashboard_base.html"%}
{% load static %}
{% load custom_tags %}
{% block title%}Dashboard{% endblock%}
{% block content %}
<link rel="stylesheet" href="{% static 'css/post.css' %}">



<div class="upper-filter mt-5" style="display: grid;grid-template-columns: 1fr 4fr;text-align: center;">
    <div>
        <h5>Feeds</h5>
    </div>
    <div class="filter-menu d-flex justify-content-end">
        <p class="me-3 grey-color" style="cursor: pointer;text-decoration: none;" id="all_data">All</p>
        {% for field in nav_fields %}
        <p class="me-3 grey-color" style="cursor: pointer;text-decoration: none;" id='{{field}}'>{{field}}</p>
        {% endfor %}


    </div>
</div>
<div class="influencer-data">
    <div class="d-flex justify-content-center">
        <div class="spinner-grow text-dark ajaxLoader mt-5" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
    <div class="row justify-content-center mt-3" id="filter_data_post">
        {% for post in posts %}

        {% if post.influencer.influencer_id.id != request.user.id %}
        <div class="col-4">

            <div class="wrapper">
                <div class="post" style="background: url('{{post.post_img.url}}');background-size: cover;">
                    <div class="overlay">

                        <form action="" method="post" id="save_post_form">
                            {% csrf_token %}
                            <span class="savepost">
                                <button type="button" id="savepost-btn-{{post.id}}" onclick="savePost('{{post.id}}')"><i
                                        class="fas fa-bookmark"></i></button>

                                <button type="button" id="remove-saved-btn-{{post.id}}"
                                    onclick="removeSavedPost('{{post.id}}')"
                                    style="color: black; background-color: white;"><i class="fas fa-bookmark"></i>
                                </button>
                            </span>
                        </form>
                    </div>
                    <a href="{% url 'viewinf' post.id %}" class="about d-flex flex-column"
                        style="text-decoration: none; color: white;margin-top: -58px;text-align: center;">
                        <strong>@{{post.influencer.influencer_id.username}}</strong> <span>{{post.title}} | {{post.field}}</span>

                    </a>
                </div>
            </div>



        </div>
        {% endif %}

        {%endfor%}
    </div>
</div>




<script>
    let nav_fields = {{ nav_fields| safe}};
    const url_path = "{% url 'dashboardFilter' %}";
    let saved_post_list = {{ saved_post_ls }};
    let posts = {{ posts| post_id_list | safe}};
    // console.log(saved_post_list)
</script>
<script src="{% static 'js/dashboard.js' %}"></script>

{% endblock%}

app/templates/dashboard_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <style>
        .hidden{
            visibility: hidden;
        }
        .alert-box {
            position: absolute;
            right: 0;
            background-color: #222831b6;
            font-size: 20px;
            padding: 15px 40px 15px 15px;
            color: white;
            top: 100px;
            min-width: 350px;
            z-index: 10;

        }

        .alert-box .close-alert {
            font-size: 20px;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            position: absolute;
            right: 10px;
            top: 15px;
            cursor: pointer;
            z-index: 11;
        }

        .alert-box.show::before {
            content: '';
            position: absolute;
            left: 0;
            bottom: 0;
            height: 4px;
            background-color: #00adb5;
            width: 100%;
            box-sizing: border-box;
            z-index: 11;
            animation: hideMeter 6s linear;
        }

        @keyframes hideMeter {
            0% {
                width: 100%;
            }

            100% {
                width: 0%;
            }
        }

        .alert-box.show {
            animation: showAlert 1s ease forwards;
        }

        @keyframes showAlert {
            0% {
                transform: translateX(100%);
            }

            40% {
                transform: translateX(-15%);
            }

            80% {
                transform: translateX(0%);
            }

            100% {
                transform: translateX(-10px);
            }
        }

        
    </style>
</head>

<body>
    {% include "navbar.html" %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert-box hide hidden">{{ message }} <span class="close-alert">&times;</span></div>
    {% endfor %}
    {% endif %}
    {% include "sidebars/left.html" %}
    
    
    <div class="content mt-5">
        {% block content %}
        
        {% endblock content %}
        
    </div>
    
    {% include "sidebars/right.html" %}





    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        const csrftoken = getCookie('csrftoken');

        const alertBox=document.querySelector(".alert-box");
        const closeBtn=document.querySelector(".close-alert")
        let timer;
        showAlertBox()

        closeBtn.addEventListener("click",function(){
            hideAlertBox();
            clearTimeout(timer);
        })

        function showAlertBox(){
            alertBox.classList.remove("hide");
            alertBox.classList.add("show");

            if(alertBox.classList.contains("hidden")){
                alertBox.classList.remove("hidden");
            }
            timer=setTimeout(function(){
                hideAlertBox();
            },6000)
        }

        function hideAlertBox(){
            alertBox.classList.remove("show");
            alertBox.classList.add("hide");
            alertBox.classList.add("hidden");
        }

    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/influencer_post.html
{% extends "dashboard_base.html" %}
{% load static %}
{% block title %}
profile
{% endblock title %}

{% block content %}


<div class="mt-5">
    <h3 class="grey-color text-center my-3">Add Post</h3>
    <div class="card shadow card-body mx-2">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div id="personal-details">
                <div class="mb-3" style="display: none;">
                    {{form.influencer}}
                </div>
                <div class="mb-3 form-floating">
                    {{form.title}}
                    <label for="id_title">Title</label>
                </div>
                <div class="mb-3 form-floating">
                    {{form.description}}
                    <label for="id_description">Description</label>
                </div>
                <div class="mb-3 form-floating">
                    {{form.field}}
                    <label for="id_field">Field of interest</label>
                </div>
                <div class="mb-3 form-floating">
                    {{form.price}}
                    <label for="id_price">Price</label>
                </div>
                <div class="mb-3 form-floating">
                    {{form.price_desc}}
                    <label for="id_price_desc">Description about Price</label>
                </div>
                <div class="mb-3 form-floating">
                    {{form.adfield}}
                    <label for="id_field">Field of Advertisement</label>
                </div>
                <div class="mb-3 form-floating">
                    {{form.day}}
                    <label for="id_day">No. of days </label>
                </div>
                <div class=" mb-3">
                    <!-- <input type="text" value="choose profile image" id="profile-img-in" readonly style="cursor: pointer;" onclick="fileTrig()"> -->
                    <label for="id_post_img" style="color: #eee;">Post</label>
                    {{form.post_img}}

                </div>

                <div class="mb-3 mt-5 d-flex justify-content-center">
                    <button type="submit" class="btn btn-outline-dark w-50">Add Post</button>
                </div>
            </div>
        </form>
    </div>
</div>


<script>
    console.log("{{user.id}}")
    $("#id_influencer").val("{{user.id}}")
    $("input").addClass("form-control")
    $("input").prop("placeholder", "search")
    $("select").addClass("form-select")
    $("textarea").addClass("form-control")
    $("textarea").prop("placeholder", "abc")
</script>
{% endblock %}

app/templates/modal_display.html
{% extends "dashboard_base.html"%}
{% load static %}
{% load custom_tags %}
{% block title%}Display{% endblock%}
{% block content %}

<button id="modal-btn-custom" style="display: none;" data-bs-toggle="modal" data-bs-target="#ffff">
click me
</button>

<!-- Modal -->
<div class="modal fade" id="ffff" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="fffflabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="fffflabel">Add Work After Completion</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
               
                <form action="{% url 'display_modal' work.id %}" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_content_link">Link of Work</label>

                        {{work_form.content_link}}
                    </div>
                    <div style="display: none;">
                        {{work_form.is_accepted}}
                        {{work_form.influencer}}
                        {{work_form.post}}
                     {{work_form.sponsor}}
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Send</button>
                    </div>
                </form>
            </div>
            
        </div>
    </div>
</div>




<script>
    $('input').addClass('form-control')
    $('select').addClass('form-control')
    $(document).ready(()=>{
        $('#modal-btn-custom').click()
    })
</script>
{% endblock%}

app/templates/notification.html
{% extends "dashboard_base.html"%}
{% load static %}
{% load custom_tags %}
{% block title%}Notification{% endblock%}
{% block content %}

<div class="mt-5">
    <h4 class="mb-3 text-center">Notifications</h4>
    {% for work in works %}
    <div class="card card-body mb-3 shadow-sm" style="cursor: pointer;" onclick=location.href="{% url 'display_modal' work.id %}">
        <div class="row">
            <div class="col-8"><strong>{{work.post.title}}</strong> - {{work.sponsor.sponsor_id.first_name}}</div>
            <div class="col-4">
                {% if work.content_link == None %}
                <span style="color: green;">work pending..</span>
                {% else %}
                <span style="color: #af1d0a;">completed</span>
                {% endif %}

            </div>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock%}

app/templates/transaction.html
{% extends "dashboard_base.html"%}
{% load static %}
{% load custom_tags %}
{% block title%}Transaction{% endblock%}
{% block content %}
<div class="w-75 mt-5 mx-auto">
    <h4 class="text-center mb-5">Transaction Details</h4>
    {% for detail in sponsored_details %}
    <div class="card shadow-sm card-body mb-3">
        <div class="row">
            <div class="col-8">
                <p>Payment for {{detail.post.title}} is successfully transfer in your account from {{detail.sponsor.sponsor_id.first_name}}'s</p>
                <p>Transaction id - <span class="text-muted">{{detail.transaction_id}}</span> </p>
            </div>
            <div class="col-4 pe-3" style="text-align: right;"><strong style="color: green;">₹ {{detail.post.price}}</strong></div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock%}